package main

import (
	"fmt"
	"html"
	"os"
	"path/filepath"
	"strings"
	"unicode"
	"unicode/utf8"
)

func titleDisplay(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return s
	}
	r, n := utf8.DecodeRuneInString(s)
	if r == utf8.RuneError {
		return s
	}
	return string(unicode.ToUpper(r)) + s[n:]
}

// emitProfessionalDocs writes README.md, api_reference.md, and index.html per project style.
func (wg *WrapperGenerator) emitProfessionalDocs(api *API) error {
	if !wg.config.NoDocsMarkdown {
		if err := wg.emitReadme(api); err != nil {
			return err
		}
		if err := wg.emitAPIReference(api); err != nil {
			return err
		}
	}
	if !wg.config.NoHTML {
		return wg.emitIndexHTML(api)
	}
	return nil
}

func (wg *WrapperGenerator) emitReadme(api *API) error {
	path := filepath.Join(wg.config.OutputDir, "README.md")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	p := func(s string, a ...interface{}) { fmt.Fprintf(f, s, a...) }

	hdr := wg.config.PrimaryHeader
	if hdr == "" && len(api.Headers) > 0 {
		hdr = filepath.Base(api.Headers[0])
	}

	p("# %s Fuji bindings\n\n", titleDisplay(api.Name))
	p("Auto-generated by **%s** %s from `%s`. **%d** functions wrapped.\n\n",
		generatedByBrand, wg.config.Version, hdr, len(api.Functions))

	p("## Quick start\n\n```fuji\n")
	p("#include \"@%s\"\n\n", api.Name)
	p("func main() {\n")
	if ex := wg.pickExampleCall(api); ex != "" {
		p("    %s\n", ex)
	} else {
		p("    // Call library functions by name after linking wrapper.c\n")
	}
	p("}\n```\n\n")

	p("## Building\n\n")
	p("Set **`FUJI_NATIVE_SOURCES`** to **`wrapper.c`** and **`FUJI_LINKFLAGS`** so Clang finds the vendor headers and library, then:\n\n")
	p("```powershell\n")
	p("$env:FUJI_NATIVE_SOURCES = \".\\wrapper.c\"\n")
	p("$env:FUJI_LINKFLAGS = \"-I<include> -L<lib> -l%s\"\n", api.Name)
	p("fuji build game.fuji -o game.exe\n")
	p("```\n\n")
	p("```bash\n")
	p("export FUJI_NATIVE_SOURCES=\"$PWD/wrapper.c\"\n")
	p("export FUJI_LINKFLAGS=\"-I<include> -L<lib> -l%s\"\n", api.Name)
	p("fuji build game.fuji -o game\n")
	p("```\n\n")

	p("## Function categories\n\n")
	p("| Category | Count | Description |\n")
	p("|----------|-------|-------------|\n")
	cats := groupFunctionsByCategory(api.Functions)
	for _, name := range sortCategoryKeys(cats) {
		p("| %s | %d | Auto-grouped from name prefixes. |\n", name, len(cats[name]))
	}
	p("\n## Full API reference\n\nSee [api_reference.md](api_reference.md).\n\n")
	p("## License\n\nThese bindings are generated. The underlying **%s** library retains its own license — see the upstream header.\n", api.Name)
	return nil
}

func (wg *WrapperGenerator) pickExampleCall(api *API) string {
	for _, fn := range api.Functions {
		if fn.Name == "InitWindow" && len(fn.Parameters) >= 3 {
			return "InitWindow(800, 450, \"Hello\");"
		}
	}
	for _, fn := range api.Functions {
		if len(fn.Parameters) == 0 && strings.HasPrefix(fn.Name, "Get") {
			return fn.Name + "();"
		}
	}
	return ""
}

func (wg *WrapperGenerator) emitAPIReference(api *API) error {
	path := filepath.Join(wg.config.OutputDir, "api_reference.md")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	q := func(s string, a ...interface{}) { fmt.Fprintf(f, s, a...) }

	hdr := wg.config.PrimaryHeader
	if hdr == "" && len(api.Headers) > 0 {
		hdr = filepath.Base(api.Headers[0])
	}

	q("# %s API reference\n\n", api.Name)
	q("> Generated by **%s** %s from `%s`. **%d** functions.\n\n", generatedByBrand, wg.config.Version, hdr, len(api.Functions))

	cats := groupFunctionsByCategory(api.Functions)
	keys := sortCategoryKeys(cats)

	q("## Table of contents\n\n")
	for _, c := range keys {
		q("- [%s](#%s)\n", c, anchorID(c))
	}
	q("\n")

	for _, cat := range keys {
		q("## %s\n\n", cat)
		for _, fn := range cats[cat] {
			if wg.skipGlueFunction(fn) {
				continue
			}
			desc := strings.TrimSpace(fn.Documentation)
			if desc == "" {
				desc = describeFromCamelName(fn.Name)
			}
			params := wg.bindingParamList(fn)
			ret := strings.TrimSpace(fn.ReturnType)
			ret = strings.TrimPrefix(ret, "RLAPI ")
			ret = strings.TrimSpace(ret)
			sig := fn.Name + "(" + params + ")"
			if ret != "" && ret != "void" {
				sig += " → " + fujiDocTypeForCType(ret)
			}

			q("### `%s`\n\n", fn.Name)
			q("```fuji\n%s\n```\n\n", sig)
			q("%s\n\n", desc)

			if len(fn.Parameters) > 0 {
				q("**Parameters**\n\n")
				q("| Name | Type | Description |\n")
				q("|------|------|-------------|\n")
				for i, param := range fn.Parameters {
					nm := strings.TrimSpace(param.Name)
					if nm == "" {
						nm = fmt.Sprintf("arg%d", i)
					}
					ft, hint := paramDocLine(nm, param.Type)
					q("| %s | %s | %s |\n", nm, ft, hint)
				}
				q("\n")
			}
			if ret == "" || ret == "void" {
				q("**Returns:** nothing\n\n---\n\n")
			} else {
				q("**Returns:** %s\n\n---\n\n", fujiDocTypeForCType(ret))
			}
		}
	}
	return nil
}

func (wg *WrapperGenerator) emitIndexHTML(api *API) error {
	path := filepath.Join(wg.config.OutputDir, "index.html")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	hdr := html.EscapeString(wg.config.PrimaryHeader)
	if hdr == "" && len(api.Headers) > 0 {
		hdr = html.EscapeString(filepath.Base(api.Headers[0]))
	}
	lib := html.EscapeString(api.Name)

	cats := groupFunctionsByCategory(api.Functions)
	keys := sortCategoryKeys(cats)

	var nav strings.Builder
	for _, c := range keys {
		id := anchorID(c)
		nav.WriteString(fmt.Sprintf(`<li><a href="#%s">%s (%d)</a></li>`+"\n", id, html.EscapeString(c), len(cats[c])))
	}

	var main strings.Builder
	for _, cat := range keys {
		cid := anchorID(cat)
		main.WriteString(fmt.Sprintf(`<section id="%s"><h2>%s</h2>`, cid, html.EscapeString(cat)) + "\n")
		for _, fn := range cats[cat] {
			if wg.skipGlueFunction(fn) {
				continue
			}
			desc := html.EscapeString(strings.TrimSpace(fn.Documentation))
			if desc == "" {
				desc = html.EscapeString(describeFromCamelName(fn.Name))
			}
			params := wg.bindingParamList(fn)
			sig := html.EscapeString(fn.Name + "(" + params + ")")
			main.WriteString(fmt.Sprintf(
				`<article class="fn" data-name="%s"><h3><code>%s</code></h3>`+
					`<pre class="sig"><code>%s</code></pre><p>%s</p>`,
				html.EscapeString(fn.Name), html.EscapeString(fn.Name), sig, desc))
			if len(fn.Parameters) > 0 {
				main.WriteString("<table><thead><tr><th>Name</th><th>Type</th></tr></thead><tbody>")
				for i, param := range fn.Parameters {
					nm := strings.TrimSpace(param.Name)
					if nm == "" {
						nm = fmt.Sprintf("arg%d", i)
					}
					ft := fujiDocTypeForCType(param.Type)
					main.WriteString(fmt.Sprintf("<tr><td>%s</td><td>%s</td></tr>",
						html.EscapeString(nm), html.EscapeString(ft)))
				}
				main.WriteString("</tbody></table>")
			}
			main.WriteString("</article>\n")
		}
		main.WriteString("</section>\n")
	}

	page := `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>` + lib + ` API — Fuji bindings</title>
<style>
:root { --bg:#fafafa; --sidebar:#1a1a2e; --accent:#e94560; --code:#f4f4f4; --text:#222; }
html[data-theme="dark"] { --bg:#12121a; --sidebar:#0f0f18; --code:#1e1e28; --text:#eaeaea; }
* { box-sizing: border-box; }
body { margin:0; font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; background:var(--bg); color:var(--text); display:flex; min-height:100vh; }
nav.sidebar { width:260px; background:var(--sidebar); color:#eee; padding:1rem; flex-shrink:0; }
nav.sidebar a { color:#bcd; text-decoration:none; }
nav.sidebar a:hover { color:var(--accent); }
nav .logo { font-weight:700; margin-bottom:0.5rem; color:#fff; }
#theme { margin-bottom:1rem; width:100%; padding:0.35rem; cursor:pointer; border-radius:6px; border:none; }
#search { width:100%; padding:0.5rem; border-radius:6px; border:none; margin-bottom:1rem; }
main { flex:1; padding:2rem; max-width:900px; }
.fn { margin-bottom:2rem; border-bottom:1px solid #3332; padding-bottom:1.5rem; }
pre.sig { background:var(--code); padding:0.75rem; border-radius:6px; overflow:auto; position:relative; }
table { border-collapse:collapse; width:100%; margin-top:0.5rem; }
th, td { border:1px solid #4444; padding:0.35rem 0.5rem; text-align:left; }
button.copy { position:absolute; top:6px; right:6px; font-size:0.75rem; cursor:pointer; }
</style>
</head>
<body>
<nav class="sidebar">
  <div class="logo">Fuji × ` + lib + `</div>
  <button type="button" id="theme" aria-label="Toggle theme">Theme</button>
  <input type="search" id="search" placeholder="Search functions…" autocomplete="off">
  <ul class="categories">` + nav.String() + `</ul>
</nav>
<main>` + main.String() + `</main>
<script>
(function(){
  var inp = document.getElementById('search');
  if (inp) inp.addEventListener('input', function() {
    var q = (inp.value || '').toLowerCase();
    document.querySelectorAll('.fn').forEach(function(el) {
      var n = (el.dataset.name || '').toLowerCase();
      el.style.display = (!q || n.indexOf(q) !== -1) ? '' : 'none';
    });
  });
  var th = document.getElementById('theme');
  if (th) th.addEventListener('click', function() {
    var h = document.documentElement;
    h.setAttribute('data-theme', h.getAttribute('data-theme') === 'dark' ? 'light' : 'dark');
  });
  document.querySelectorAll('pre.sig').forEach(function(pre) {
    var btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'copy';
    btn.textContent = 'Copy';
    btn.addEventListener('click', function() {
      var t = pre.querySelector('code'); if (!t) return;
      navigator.clipboard.writeText(t.textContent || '');
    });
    pre.appendChild(btn);
  });
})();
</script>
</body>
</html>`
	_, err = f.WriteString(page)
	return err
}
