#!/bin/bash
# Build script for raylib wrapper
# Generated by WrapGen

set -e

echo "Building raylib wrapper..."
echo "========================"

# Check dependencies
if ! command -v pkg-config &> /dev/null; then
    echo "Error: pkg-config is required but not installed."
    exit 1
fi

if ! pkg-config --exists raylib; then
    echo "Error: raylib library not found."
    echo "Please install raylib development package."
    exit 1
fi

# Get compiler flags
CFLAGS=$(pkg-config --cflags raylib)
LIBS=$(pkg-config --libs raylib)
echo "CFLAGS: $CFLAGS"
echo "LIBS: $LIBS"

# Build with Make
if command -v make &> /dev/null; then
    echo "Building with Make..."
    make clean
    make all
    echo "Build completed successfully!"
    echo "Libraries: wrapper.so wrapper.a"
else
    echo "Make not found, building manually..."
    gcc -fPIC -shared -o wrapper.so wrapper.c $LIBS
    ar rcs wrapper.a wrapper.o
    echo "Manual build completed!"
fi

# Run tests if available
if [ -f "test_raylib" ]; then
    echo "Running tests..."
    ./test_raylib
    echo "Tests completed!"
fi

echo "Build process completed!"
echo "========================"
echo "To install: sudo make install"
echo "To test: ./test_raylib"
