/*
 * test - Fuji native glue layer
 * Auto-generated by wrapgen. Do not edit.
 *
 * This file is compiled automatically by `fuji build` and `fuji bundle`.
 * Users of the wrapper library never need to read or modify this file.
 *
 * Each function bridges a Fuji call to the native LLVM-compiled library
 * using the Fuji native ABI: FujiValue fn(int argCount, FujiValue* args)
 */

#include "fuji.h"
#include <string.h>
#include "test_wrapper.h"

/* add(int a, int b) -> int */
FujiValue fuji_wrap_test_add(int argCount, FujiValue* args) {
    if (argCount < 2) return NULL_VAL;
    int arg0 = (IS_NUMBER(args[0]) ? AS_NUMBER(args[0]) : 0);
    int arg1 = (IS_NUMBER(args[1]) ? AS_NUMBER(args[1]) : 0);
    int result = add(arg0, arg1);
    return NUMBER_VAL((double)result);
}

/* multiply(double a, double b) -> double */
FujiValue fuji_wrap_test_multiply(int argCount, FujiValue* args) {
    if (argCount < 2) return NULL_VAL;
    double arg0 = (IS_NUMBER(args[0]) ? AS_NUMBER(args[0]) : 0);
    double arg1 = (IS_NUMBER(args[1]) ? AS_NUMBER(args[1]) : 0);
    double result = multiply(arg0, arg1);
    return NUMBER_VAL((double)result);
}

/* print_hello(const char* message) -> void */
FujiValue fuji_wrap_test_print_hello(int argCount, FujiValue* args) {
    if (argCount < 1) return NULL_VAL;
    const char* arg0 = (IS_OBJ(args[0]) && AS_OBJ(args[0])->type == OBJ_STRING ? ((FujiString*)AS_OBJ(args[0]))->chars : "");
    print_hello(arg0);
    return NULL_VAL;
}

