/* ============================================================
 *  wrapper.c
 *  Auto-generated by fujiwrap 0.2.0-dev
 *  Source:  minimal.h
 *  Generated: 2026-05-05T04:48:26Z
 *
 *  Link with fuji build (FUJI_NATIVE_SOURCES includes this file).
 * ============================================================ */

#include "fuji_wrapgen_abi.h"
#include <stdbool.h>
#include <string.h>
#include "minimal.h"

/* ------------------------------------------------------------ */
/*  Miscellaneous                                              */
/* ------------------------------------------------------------ */

/**
 * fuji_wrap_minimal_wg_add — Fuji wrapper for wg_add
 *
 * Fuji call:  wg_add(a, b)
 *   a : number → int
 *   b : number → int
 *   returns: number
 */
FujiValue fuji_wrap_minimal_wg_add(int argCount, FujiValue* args) {
    if (argCount < 2) {
        return fuji_err_str("wg_add requires 2 argument(s)");
    }
    int arg0 = (IS_NUMBER(args[0]) ? (int)AS_NUMBER(args[0]) : 0);
    int arg1 = (IS_NUMBER(args[1]) ? (int)AS_NUMBER(args[1]) : 0);
    int result = wg_add(arg0, arg1);
    return NUMBER_VAL((double)result);
}

/**
 * fuji_wrap_minimal_wg_reset — Fuji wrapper for wg_reset
 *
 * Fuji call:  wg_reset()
 *   returns: nothing
 */
FujiValue fuji_wrap_minimal_wg_reset(int argCount, FujiValue* args) {
    if (argCount < 0) {
        return fuji_err_str("wg_reset requires 0 argument(s)");
    }
    wg_reset();
    return NULL_VAL;
}

